#pragma once

// 选择网络实现
// #define STEALTHIM_NETWORK_WIN32 1
#define STEALTHIM_NETWORK_POSIX 1
// #define STEALTHIM_NETWORK_LWIP 1


// 选择日志实现
#define STEALTHIM_LOG_ENABLED 1

#define STEALTHIM_LOG_STDIO 1
// #define STEALTHIM_LOG_CUSTOM 1
// #define STEALTHIM_LOG_NONE 1

#define STEALTHIM_LOG_DEBUG 0
#define STEALTHIM_LOG_INFO 1
#define STEALTHIM_LOG_WARN 2
#define STEALTHIM_LOG_ERROR 3
#define STEALTHIM_LOG_NONE 4

#define STEALTHIM_LOG_LEVEL STEALTHIM_LOG_DEBUG

// 选择 TLS 实现
#define STEALTHIM_TLS_OPENSSL 1
// #define STEALTHIM_TLS_MBEDTLS 1

// 选择 WebSocket 实现
// #define STEALTHIM_WS_WIN32 1
#define STEALTHIM_WS_POSIX 1
// #define STEALTHIM_WS_NONE 1

// 选择 Async 实现
// #define STEALTHIM_ASYNC_WIN32 1
#define STEALTHIM_ASYNC_LINUX 1
// #define STEALTHIM_ASYNC_BSD 1
