#pragma once

// 选择网络实现
#define STEALTHIM_NETWORK_WIN32 1
// #define STEALTHIM_NETWORK_POSIX 1
// #define STEALTHIM_NETWORK_LWIP 1


// 选择日志实现
#define STEALTHIM_LOG_ENABLED 1

#define STEALTHIM_LOG_STDIO 1
// #define STEALTHIM_LOG_CUSTOM 1
// #define STEALTHIM_LOG_NONE 1

#define STEALTHIM_LOG_DEBUG 0
#define STEALTHIM_LOG_INFO 1
#define STEALTHIM_LOG_WARN 2
#define STEALTHIM_LOG_ERROR 3
#define STEALTHIM_LOG_NONE 4

#define STEALTHIM_LOG_LEVEL STEALTHIM_LOG_DEBUG
